import { prepareSolverInput, buildSeedSolution } from './dataPrep';
import type { SubjectFull, TimetableSlotRow } from './dataPrep';
import { evaluate } from './constraints';
import type { Group, Room } from '../hooks/useGeneratorData';
import type { FitnessResult } from './types';

/**
 * Evaluates an external timetable generated by a different algorithm
 * against the rigorous constraints defined in the current solver.
 * 
 * @param subjects - The list of subjects with L-T-P configurations.
 * @param groups - The student groups (sections).
 * @param professors - The list of professors.
 * @param rooms - The available rooms.
 * @param assignments - Professor assignment map: subjectId -> groupId -> professorId
 * @param homeRooms - Home room map: groupId -> roomId
 * @param externalSlots - The timetable slots generated by the external algorithm.
 * 
 * @returns A detailed fitness report containing all hard violations and the soft gap penalty.
 */
export function evaluateExternalTimetable(
    subjects: SubjectFull[],
    groups: Group[],
    professors: { id: string; name: string }[],
    rooms: Room[],
    assignments: Record<string, Record<string, string>>,
    homeRooms: Record<string, string>,
    externalSlots: TimetableSlotRow[]
): { fitness: FitnessResult; missingSlots: number } {

    // 1. Prepare the exact problem definition the solver expects.
    // This generates the ClassSession array (all the classes that MUST be scheduled).
    const input = prepareSolverInput(subjects, groups, professors, rooms, assignments, homeRooms);

    // 2. Convert the external slots into a "Solution" format (array of Genes).
    // buildSeedSolution takes the raw slots (day, time, room) and maps them to the required sessions.
    const solution = buildSeedSolution(input, externalSlots);

    // 3. Sanity Check: Did the external algorithm actually schedule all required sessions?
    // buildSeedSolution uses a random fallback for sessions that weren't found in externalSlots.
    // We can loosely detect this if the external slots array length doesn't match the required sessions length.
    // (Note: This is an approximation. A more robust check would verify every single gene is not randomized).
    const missingSlots = Math.max(0, input.sessions.length - externalSlots.length);

    // 4. Run the exact constraint evaluations.
    const fitness = evaluate(input, solution);

    return {
        fitness,
        missingSlots
    };
}

/**
 * Example usage:
 * 
 * const externalData = [
 *   {
 *     subject_id: "uuid-1",
 *     student_group_id: "uuid-2",
 *     room_id: "uuid-3",
 *     day_of_week: 1, // Monday
 *     start_time: "09:50",
 *     end_time: "10:50",
 *     slot_type: "Lecture"
 *   },
 *   // ... rest of the external timetable
 * ];
 * 
 * const report = evaluateExternalTimetable(
 *    dbSubjects, dbGroups, dbProfessors, dbRooms, assignments, homeRooms, externalData
 * );
 * 
 * console.log("Hard Violations: ", report.fitness.hardViolations);
 * console.log("Detailed Breakdown: ", report.fitness.violationBreakdown);
 */
